SKADIS_HOLE_TO_HOLE_DISTANCE = 40;
SKADIS_HOLE_WIDTH = 5;
SKADIS_HOLE_HEIGHT = 10; // excluding the rounded edges
SKADIS_HOLE_DEPTH = 6;
SKADIS_HOOK_ADAPTER_OUTER_WIDTH = 10;
SKADIS_HOOK_ADAPTER_INNER_WIDTH = 14;
SKADIS_HOOK_ADAPTER_OUTER_DEPTH = 2;
SKADIS_HOOK_ADAPTER_INNER_DEPTH = 2;